// Code generated by "stringer -type Token"; DO NOT EDIT.

package lang

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Unexpected-1]
	_ = x[Newline-2]
	_ = x[Comment-3]
	_ = x[LiteralInt-4]
	_ = x[LiteralFloat-5]
	_ = x[LiteralStr-6]
	_ = x[OpenBrace-7]
	_ = x[CloseBrace-8]
	_ = x[OpenParen-9]
	_ = x[CloseParen-10]
	_ = x[OpenBracket-11]
	_ = x[CloseBracket-12]
	_ = x[Comma-13]
	_ = x[Semicolon-14]
	_ = x[Colon-15]
	_ = x[Assign-16]
	_ = x[Plus-17]
	_ = x[Dash-18]
	_ = x[Star-19]
	_ = x[Slash-20]
	_ = x[Equal-21]
	_ = x[NotEqual-22]
	_ = x[LessThan-23]
	_ = x[GreaterThan-24]
	_ = x[LessEqual-25]
	_ = x[GreaterEqual-26]
	_ = x[And-27]
	_ = x[Or-28]
	_ = x[Elvis-29]
	_ = x[Rocket-30]
	_ = x[Arrow-31]
	_ = x[Not-32]
	_ = x[Dot-33]
	_ = x[Dollar-34]
	_ = x[If-35]
	_ = x[Else-36]
	_ = x[In-37]
	_ = x[As-38]
	_ = x[Class-39]
	_ = x[Include-40]
	_ = x[Import-41]
	_ = x[Func-42]
	_ = x[Bool-43]
	_ = x[Str-44]
	_ = x[Int-45]
	_ = x[Float-46]
	_ = x[Map-47]
	_ = x[Struct-48]
	_ = x[Variant-49]
	_ = x[True-50]
	_ = x[False-51]
	_ = x[Identifier-52]
	_ = x[CapitalizedIdentifier-53]
	_ = x[ResIdentifier-54]
}

const _Token_name = "EOFUnexpectedNewlineCommentLiteralIntLiteralFloatLiteralStrOpenBraceCloseBraceOpenParenCloseParenOpenBracketCloseBracketCommaSemicolonColonAssignPlusDashStarSlashEqualNotEqualLessThanGreaterThanLessEqualGreaterEqualAndOrElvisRocketArrowNotDotDollarIfElseInAsClassIncludeImportFuncBoolStrIntFloatMapStructVariantTrueFalseIdentifierCapitalizedIdentifierResIdentifier"

var _Token_index = [...]uint16{0, 3, 13, 20, 27, 37, 49, 59, 68, 78, 87, 97, 108, 120, 125, 134, 139, 145, 149, 153, 157, 162, 167, 175, 183, 194, 203, 215, 218, 220, 225, 231, 236, 239, 242, 248, 250, 254, 256, 258, 263, 270, 276, 280, 284, 287, 290, 295, 298, 304, 311, 315, 320, 330, 351, 364}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
